name: Publish docker image to amazon ecr

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build image and publish to amazon ecr
    runs-on: ubuntu-latest

    steps:
      - name: repository checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret_access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to amazon ecr
        id: login-ecr
        uses: aws-actions-amazon-ecr-login@v2

      - name: Buils ans push docker image to amazon ecr
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.output.registry}}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/${{REPOSITORY_NAME}}:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/${{REPOSITORY_NAME}}:$IMAGE_TAG
